// Të dhëna mock për mockup-et e Konsum

export const HERO_SLIDES = [
  {
    id: 1,
    title: 'Ofertat Javore',
    subtitle: 'Zbritje deri në 50% në qindra produkte',
    cta: 'Shiko Ofertat',
    href: '/oferta',
    image: 'https://images.unsplash.com/photo-1642582034088-860e69149ef4?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjAzMzl8MHwxfHNlYXJjaHwyfHxzdXBlcm1hcmtldHxlbnwwfHx8cmVkfDE3ODIxNzc4NTF8MA&ixlib=rb-4.1.0&q=85',
    badge: 'E RE',
  },
  {
    id: 2,
    title: 'Fruta & Perime të Freskëta',
    subtitle: 'Drejt nga ferma në tavolinën tuaj',
    cta: 'Shiko Produktet',
    href: '/oferta?kategori=fruta-perime',
    image: 'https://images.unsplash.com/photo-1647924124055-5256a05159e6?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDQ2NDJ8MHwxfHNlYXJjaHwxfHxmcmVzaCUyMHByb2R1Y2V8ZW58MHx8fHJlZHwxNzgyMTc3ODY3fDA&ixlib=rb-4.1.0&q=85',
    badge: 'FRESKËT',
  },
  {
    id: 3,
    title: 'Familja jonë, Familja juaj',
    subtitle: 'Bleni më shumë, kurseni më shumë çdo ditë',
    cta: 'Mëso më shumë',
    href: '/rreth-nesh',
    image: 'https://images.unsplash.com/photo-1661193302766-300b3713aabd?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1NjZ8MHwxfHNlYXJjaHwzfHxncm9jZXJ5fGVufDB8fHxyZWR8MTc4MjE3Nzg1MXww&ixlib=rb-4.1.0&q=85',
    badge: 'KONSUM',
  },
]

export const CATEGORIES = [
  { slug: 'te-gjitha', name: 'Të Gjitha', icon: '🛒' },
  { slug: 'fruta-perime', name: 'Fruta & Perime', icon: '🥬' },
  { slug: 'mish-peshk', name: 'Mish & Peshk', icon: '🥩' },
  { slug: 'qumeshtore', name: 'Qumështore', icon: '🥛' },
  { slug: 'buke-pasterici', name: 'Bukë & Pastiçeri', icon: '🥖' },
  { slug: 'pije', name: 'Pije', icon: '🥤' },
  { slug: 'enje-shtepiake', name: 'Enë Shtëpiake', icon: '🧴' },
  { slug: 'embelsira', name: 'Ëmbëlsira', icon: '🍫' },
]

export const OFFERS = [
  {
    id: 'o1',
    name: 'Mish Viçi i Freskët',
    category: 'mish-peshk',
    image: 'https://images.unsplash.com/photo-1603048297172-c92544798d5a?w=600&q=80',
    oldPrice: 599,
    newPrice: 399,
    unit: 'kg',
    badge: '-33%',
    active: true,
  },
  {
    id: 'o2',
    name: 'Domate Lokale',
    category: 'fruta-perime',
    image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=600&q=80',
    oldPrice: 89,
    newPrice: 49,
    unit: 'kg',
    badge: '-45%',
    active: true,
  },
  {
    id: 'o3',
    name: 'Qumësht i Plotë 1L',
    category: 'qumeshtore',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&q=80',
    oldPrice: 75,
    newPrice: 59,
    unit: 'copë',
    badge: '-21%',
    active: true,
  },
  {
    id: 'o4',
    name: 'Bukë e Bardhë 500g',
    category: 'buke-pasterici',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&q=80',
    oldPrice: 45,
    newPrice: 29,
    unit: 'copë',
    badge: '-35%',
    active: true,
  },
  {
    id: 'o5',
    name: 'Mollë të Kuqe Premium',
    category: 'fruta-perime',
    image: 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=600&q=80',
    oldPrice: 79,
    newPrice: 49,
    unit: 'kg',
    badge: '-38%',
    active: true,
  },
  {
    id: 'o6',
    name: 'Coca-Cola 2L',
    category: 'pije',
    image: 'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=600&q=80',
    oldPrice: 149,
    newPrice: 99,
    unit: 'copë',
    badge: '-34%',
    active: true,
  },
  {
    id: 'o7',
    name: 'Djathë i Bardhë 500g',
    category: 'qumeshtore',
    image: 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=600&q=80',
    oldPrice: 299,
    newPrice: 199,
    unit: 'copë',
    badge: '-33%',
    active: true,
  },
  {
    id: 'o8',
    name: 'Çokollatë Milka 100g',
    category: 'embelsira',
    image: 'https://images.unsplash.com/photo-1623660053975-cf75a8be0908?w=600&q=80',
    oldPrice: 99,
    newPrice: 69,
    unit: 'copë',
    badge: '-30%',
    active: true,
  },
  {
    id: 'o9',
    name: 'Pulë e Freskët',
    category: 'mish-peshk',
    image: 'https://images.unsplash.com/photo-1602470520998-f4a52199a3d6?w=600&q=80',
    oldPrice: 249,
    newPrice: 179,
    unit: 'kg',
    badge: '-28%',
    active: true,
  },
  {
    id: 'o10',
    name: 'Detergjent Ariel 3L',
    category: 'enje-shtepiake',
    image: 'https://images.unsplash.com/photo-1583947581924-860bda3c4f31?w=600&q=80',
    oldPrice: 599,
    newPrice: 399,
    unit: 'copë',
    badge: '-33%',
    active: true,
  },
  {
    id: 'o11',
    name: 'Banane Premium',
    category: 'fruta-perime',
    image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=600&q=80',
    oldPrice: 89,
    newPrice: 59,
    unit: 'kg',
    badge: '-34%',
    active: true,
  },
  {
    id: 'o12',
    name: 'Ujë Mineral 1.5L',
    category: 'pije',
    image: 'https://images.unsplash.com/photo-1564419320461-6870880221ad?w=600&q=80',
    oldPrice: 35,
    newPrice: 25,
    unit: 'copë',
    badge: '-29%',
    active: true,
  },
]

export const LOCATIONS = [
  {
    id: 'l1',
    name: 'Konsum Qendër',
    address: 'Bul. Partizanski Odredi 12, 1000 Shkup',
    phone: '+389 2 312 3456',
    hours: 'E Hënë - E Diel: 07:00 - 22:00',
    mapUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d11856.41!2d21.4144!3d41.9981!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zNDHCsDU5JzUzLjIiTiAyMcKwMjQnNTEuOCJF!5e0!3m2!1ssq!2smk!4v1000000000000',
  },
  {
    id: 'l2',
    name: 'Konsum Çair',
    address: 'Rr. Çair 45, 1000 Shkup',
    phone: '+389 2 322 4567',
    hours: 'E Hënë - E Diel: 07:00 - 23:00',
    mapUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d11856!2d21.43!3d42.01',
  },
  {
    id: 'l3',
    name: 'Konsum Tetovë',
    address: 'Bul. Ilinden 78, 1200 Tetovë',
    phone: '+389 44 333 678',
    hours: 'E Hënë - E Shtunë: 07:00 - 22:00, E Diel: 08:00 - 20:00',
    mapUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d11900!2d20.97!3d42.01',
  },
  {
    id: 'l4',
    name: 'Konsum Gostivar',
    address: 'Rr. Beliçica 23, 1230 Gostivar',
    phone: '+389 42 444 789',
    hours: 'E Hënë - E Diel: 07:30 - 21:30',
    mapUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d11920!2d20.91!3d41.79',
  },
]

export const SITE = {
  brand: 'KONSUM',
  tagline: 'Çdo ditë, çmime të mira',
  phone: '+389 2 312 3456',
  email: 'info@konsum.mk',
  address: 'Bul. Partizanski Odredi 12, 1000 Shkup, Maqedoni',
  hours: 'E Hënë - E Diel: 07:00 - 22:00',
  social: {
    facebook: 'https://facebook.com/konsum',
    instagram: 'https://instagram.com/konsum',
    youtube: 'https://youtube.com/konsum',
    tiktok: 'https://tiktok.com/@konsum',
  },
}

export const ABOUT_CONTENT = {
  hero_title: 'Rreth Konsum',
  hero_subtitle: 'Tregtari juaj i besueshëm që nga viti 1991',
  history: 'Konsum filloi rrugëtimin e tij në vitin 1991 si një dyqan i vogël familjar në Shkup. Sot, ne jemi një nga rrjetet më të mëdha të supermarketeve në Maqedoni, me dhjetëra lokacione në të gjithë vendin dhe mijëra klientë të kënaqur çdo ditë. Misioni ynë mbetet i njëjtë: të ofrojmë produkte cilësore me çmime të arsyeshme për çdo familje.',
  mission: 'Të jemi zgjedhja e parë e familjeve maqedonase për blerjet ditore, duke ofruar produkte të freskëta, cilësore dhe me çmime konkurruese.',
  vision: 'Të bëhemi rrjeti më i besueshëm i supermarketeve në rajon, i njohur për cilësinë, shërbimin dhe ofertat e mrekullueshme.',
  values: [
    { title: 'Cilësia', desc: 'Vetëm produktet më të mira për familjen tuaj.' },
    { title: 'Freskia', desc: 'Fruta, perime dhe mish të freskët çdo ditë.' },
    { title: 'Çmimi i drejtë', desc: 'Çmime të arsyeshme dhe oferta të vërteta.' },
    { title: 'Shërbimi', desc: 'Stafi ynë i përkushtuar është gjithmonë në shërbimin tuaj.' },
  ],
  policies: [
    { title: 'Politika e Kthimit', desc: 'Mund të ktheni produktet brenda 14 ditësh me kushtin që të jenë në gjendje origjinale dhe me faturë.' },
    { title: 'Garanci Cilësie', desc: 'Të gjitha produktet tona janë garantuar të jenë të freskëta dhe me cilësi.' },
    { title: 'Privatësia', desc: 'Të dhënat tuaja personale janë të mbrojtura sipas ligjeve maqedonase dhe direktivave të BE-së.' },
  ],
  delivery: 'Konsum ofron dërgesë në shtëpi për porositë mbi 1000 MKD brenda zonës urbane të Shkupit. Dërgesa kryhet brenda 2 orësh nga konfirmimi i porosisë.',
}

export const DASHBOARD_STATS = {
  active_offers: 24,
  total_products: 156,
  total_locations: 12,
  recent_updates: 8,
  weekly_visits: 12450,
  conversion_rate: 4.2,
}

export const RECENT_ACTIVITY = [
  { id: 1, action: 'Ofertë e re u shtua', item: 'Mish Viçi i Freskët', time: '2 orë më parë', user: 'admin' },
  { id: 2, action: 'Çmimi u përditësua', item: 'Domate Lokale', time: '4 orë më parë', user: 'admin' },
  { id: 3, action: 'Banner i ri u ngarkua', item: 'Hero Slide #3', time: '1 ditë më parë', user: 'admin' },
  { id: 4, action: 'Lokacion i ri u shtua', item: 'Konsum Gostivar', time: '2 ditë më parë', user: 'admin' },
  { id: 5, action: 'Ofertë u deaktivizua', item: 'Vaj Ulliri 1L', time: '3 ditë më parë', user: 'admin' },
]
